sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.24.1

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
    > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
addons:
  apt:
    packages:
    - sshpass
script:
  # Test&Build
  - docker-compose build app
  - docker save -o dashboard.tar testokur-dashboard:latest
  - sshpass -p $SSH_PASSWORD scp dashboard.tar $SSH_USERNAME@$SSH_HOST:/home/docker-images/
after_success:
  - sshpass -p $SSH_PASSWORD ssh  $SSH_USERNAME@$SSH_HOST 'bash -s' < deploy.sh
notifications:
  email:
    - nazmialtun@windowslive.com
