sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.24.1

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
    > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  # Test&Build
  - docker-compose build app
after_success:
  # Deploy
  - scp dashboard.tar $SSH_USERNAME@$SSH_HOST:/home/docker-images/
  - ssh  $SSH_USERNAME@$SSH_HOST 'bash -s' < deploy.sh
notifications:
  email:
    - nazmialtun@windowslive.com
