version: '3.7'

services:
  sonar:
    image: testokur-dashboard-sonar:latest
    build:
      context: .
      dockerfile: sonar.Dockerfile
  app:
    image: testokur-dashboard-ui:latest
    build: .
    ports:
      - '5080:80'
    volumes:
      - npm-cache:/root/.npm
  mock-webapi:
    image: nazmialtun/mockizen:latest
    volumes:
      - ./mocks/webapi:/opt/app/mocks
    expose:
      - '8080'
    ports:
      - '8097:8080'
  mock-identity:
    image: nazmialtun/mockizen:latest
    volumes:
      - ./mocks/identity:/opt/app/mocks
    expose:
      - '8080'
    ports:
      - '8098:8080'
volumes:
  npm-cache:
