version: '3.7'

services:
  sonar:
    image: testokur-dashboard-sonar:latest
    build:
      context: .
      dockerfile: sonar.Dockerfile
  app:
    image: testokur-dashboard:latest
    build: .
    ports:
      - '5080:80'
    environment:
      - 'authority=https://kimlik-qa.testokur.com'
    volumes:
      - npm-cache:/root/.npm
  mock:
    image: nazmialtun/mockizen:latest
    volumes:
      - ./mocks:/opt/app/mocks
    expose:
      - '8080'
    ports:
      - '8097:8080'
volumes:
  npm-cache:
