version: 2.1
defaults: &defaults
  working_directory: ~/repo
  machine: true
jobs:
  environment:
    IMAGE_NAME: nazmialtun/testokur-dashboard-ui
  static-code-analysis:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Static Code Analysis
          command: |
            docker-compose build --build-arg SONAR_TOKEN=$SONAR_TOKEN sonar
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Test&Build
          command: |
            docker-compose build --build-arg CODECOV_TOKEN=$CODECOV_TOKEN  app
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
                docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
                docker push $IMAGE_NAME:latest
                docker push $IMAGE_NAME:$IMAGE_TAG
      - persist_to_workspace:
          root: ~/repo
          paths:
            - deploy.sh
            - deploy-prod.sh
  deploy-qa:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run container
          command: |
            ssh  $SSH_USERNAME@$QA_SERVER 'bash -s' < deploy.sh > /dev/null
  deploy-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run container
          command: |
            ssh  $SSH_USERNAME@$PROD_SERVER 'bash -s' < deploy-prod.sh > /dev/null
workflows:
  version: 2
  dashboard-ui:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - static-code-analysis:
          filters:
            tags:
              only: /.qa*/
      - deploy-qa:
          requires:
            - static-code-analysis
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
