version: 2
jobs:
   build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Test&Build
          command: |
            docker-compose build app
      - deploy:
          name: compress the image file
          command: |
            docker save -o dashboard.tar testokur-dashboard:latest

