version: 2.1
defaults: &defaults
  working_directory: /tmp
  machine: true
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Static Code Analysis
          command: |
            docker-compose build --build-arg SONAR_TOKEN=$SONAR_TOKEN sonar
      - run:
          name: Test&Build
          command: |
            docker-compose build --build-arg CODECOV_TOKEN=$CODECOV_TOKEN  app
      - run:
          name: Compress the image file
          command: |
            docker save -o dashboard.tar testokur-dashboard:latest
      - persist_to_workspace:
          root: workspace
          paths:
            - dashboard.tar
            - deploy.sh
            - deploy-prod.sh
  deploy-qa:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy image to the app server
          command: |
            scp -q dashboard.tar $SSH_USERNAME@$SSH_HOST:/home/docker-images/
      - run:
          name: Run container
          command: |
            ssh  $SSH_USERNAME@$SSH_HOST 'bash -s' < deploy.sh
  deploy-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run container
          command: |
            ssh  $SSH_USERNAME@$SSH_HOST 'bash -s' < deploy-prod.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
